import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from './component/banner'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pragatheeswaran</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
    </div>
  )
}
