import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from './component/banner';
import Career from './component/career';
import OwnProjects from './component/ownProjects';
import Company from './component/company';
import Footer from './component/footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pragatheeswaran</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative px-4 py-3 text-white bg-indigo-600 pr-14">
  <p className="text-sm font-medium text-left sm:text-center">
      This page is under construction, would you like more information about me?
    <a className="underline" href="https://pragi.vercel.app/portfolio"> Learn More &rarr; </a>
  </p>
</div>
      <Banner />
      <Career />
      <OwnProjects />
      <Company />
      <Footer />
    </div>
  )
}
